### ISSUE TITLE
use text field to select dates

### ISSUE THREAD

**Issue by barodeur** [ares-ensiie/intranet#1]
![Screenshot_2_19_13_10_52_PM](https://f.cloud.github.com/assets/303170/173500/c4e7d55e-7ade-11e2-8a31-7d4ae01bbf67.png)

**Comment by Soulou** [comment]
Je vois trois choix :
- Traduire les mois
- Calendar Jquery-like
- Simple textfield

**Comment by barodeur** [comment]
I think we should use this plugin http://www.eyecon.ro/bootstrap-datepicker/

**Comment by Soulou** [comment]
Ok I'm doing it !
