### ISSUE TITLE
Responsiveness issues

### ISSUE THREAD

**Issue by barodeur** [ares-ensiie/intranet#4]
![IntranetSXB-4](https://f.cloud.github.com/assets/303170/173682/33767976-7ae4-11e2-9ae5-47ab90a15624.png)

**Comment by Soulou** [comment]
It's not good for me, the page is too large, i've an horizontal slider when my zoom level is normal (100%)

**Comment by barodeur** [comment]
I'm sure it's because of your footer ! :-)

**Comment by Soulou** [comment]
Nop that's the 

body -> #wrap -> .container-fluid -> .span10 -> .container
