### ISSUE TITLE
Sort promotion by name

### ISSUE THREAD

**Issue by gaultier** [ares-ensiie/intranet#63]
Currently: 
2016 < 2012 <  2013 < 2014 < 2015 
on http://www.iiens.eu/trombi/promotions/2015
which is surprising because in app/models/promotion.rb we have this line that should work:
`default_scope order_by([:name, :asc])`

**Comment by barodeur** [comment]
There was a space in the promotion name... `" 2016"`.... I just fixed that and sorted it `desc` so old promotions are at the bottom of the list.
